name: build-docs
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            mkdocs
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: mkdocs build --config-file mkdocs.yml
        if: github.ref != 'refs/heads/main'
      - run: mkdocs gh-deploy --config-file mkdocs.yml --force
        if: github.ref == 'refs/heads/main'
